### ISSUE TITLE
User.php:44-44: Prevent user from being multiple...

### ISSUE THREAD

**Issue by 0pdd** [pivot-libre/pivot#2]
The puzzle `1-3503b678` in [`app/User.php`](https://github.com/pivot-libre/pivot/blob/master/app/User.php) (lines 44-44) has to be resolved: "Prevent user from being multiple electors */"

The puzzle was created by Andrew Shell on 19-May-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@andrewshell please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `1-3503b678` has disappeared from the source code, that's why I closed this issue. //cc @andrewshell

**Comment by tylerharter** [comment]
In order to make sure double voting can never happened, I added a DB unique constraint so that we can never have the same user_id acting as multiple electors on the same election_id.  This is added with this migration: 2018_02_20_033939_add_unique_electors_constraint.php.

Of course, if there are already duplicates in your DB, you'll need to clean them up before you can run the migration successfully.
