### ISSUE TITLE
Make Registration Easy

### ISSUE THREAD

**Issue by carlschroedl** [pivot-libre/pivot#200]
As grandma I want to register so that I can see what all the hullabaloo is about this "Ranked Pairs" voting the whippersnappers are talking about.

**Comment by carlschroedl** [comment]
Can we simplify the user experience by splitting this into two pages?
 1. Enter email address. On form submit, it sends registration email.
 2. Complete registration. Users arrive at this page by clicking on the token-endowed link in their email. The user's email address is displayed on the page. Users complete sign-up by entering their name and password.

**Comment by carlschroedl** [comment]
Changes to the registration pages would potentially break the selenium-driven `create_users` [function in tests.py](https://github.com/pivot-libre/pivot/blob/master/tests/python/tests.py#L472). I notice our build doesn't use this functionality by default; instead it uses the TravisSeeder class to achieve the same results. If breaking changes to the registration pages occur, what should we do with the `create_users` Python function? Fix it? Delete it?

**Comment by tylerharter** [comment]
I like the suggestion about splitting into two pages (or at least make it feel like two different pages with JS).

**Comment by tylerharter** [comment]
I'm fine getting rid of create_users, unless you think it's useful for testing purposes.

I added create_users because I didn't know about the Laravel seeding stuff, and I wanted some way to create users automatically.  @olivernybroe later added the seeding, which I think is cleaner.

Personally, I would delete create_users for now, and add it back later only if we want to have selenium tests of registration.

**Comment by carlschroedl** [comment]
Thanks for the helpful context and for weighing in on the suggestion!

**Comment by olivernybroe** [comment]
You can also do selenium testing directly in Laravel, think it's called Laravel Dusk
