### ISSUE TITLE
Rank endpoints

### ISSUE THREAD

**Issue by aditya-cherukuri** [pivot-libre/pivot#44]
Looking on thoughts for a few questions.

1. What should be return when hitting the index endpoint of the CandidateRankController?

I think that it should return the ranks of all candidates in the election. Is that correct? If yes I think I have to wait for the rank calculation logic to be plugged in before I make more progress.

2. What should be return when hitting the show endpoint of the CandidateRankController?

Currently it's set to accept the election, candidate and rank and then return the result. I'm not sure what is the benefit of having this endpoint as there is no further information connected to the rank. Or do we want the list of electors who assigned a known rank for a known candidate in an election?

3. New Controller for ElectorCandidateRankController

I think we need to have a controller that will have endpoints that looks at ranks from an elector's perspective. This is what I think should be supported:

Index: Show the ranks for all candidates of an election for a specific elector
Store: Don't need this since it's already implemented by CandidateRankController@store
Show: Show the rank for a specific candidate of an election for a specific elector
Put: Update the rank for a specific candidate of an election for a specific elector

**Comment by carlschroedl** [comment]
Good questions Adi! I don't have time to look at code to answer your
questions,  ridge now but I do have time to answer based on what I
overheard Tyler and Nathan talking about at the last work session. I was
drifting in and out of their conversations while I was troubleshooting
Vagrant problems. For this reason, Tyler and Nathan are better sources than
I am. The source code is a better source than I am too :)

Looking on thoughts for a few questions.

   1. What should be return when hitting the index endpoint of the
   CandidateRankController?

I think that it should return the ranks of all candidates in the election.
Is that correct? If yes I think I have to wait for the rank calculation
logic to be plugged in before I make more progress.

Yep, I think it's just the ranks of all candidates in the election. I think
Tyler merged something that mocks this. Is the mock response good enough to
work with for now? We are hoping to hook up the real result calculations
soon.


   1. What should be return when hitting the show endpoint of the
   CandidateRankController?

Currently it's set to accept the election, candidate and rank and then
return the result. I'm not sure what is the benefit of having this endpoint
as there is no further information connected to the rank. Or do we want the
list of electors who assigned a known rank for a known candidate in an
election?

I don't think we would need that endpoint. Nathan would know better than I.


   1. New Controller for ElectorCandidateRankController



I think we need to have a controller that will have endpoints that looks at
ranks from an elector's perspective. This is what I think should be
supported:

Index: Show the ranks for all candidates of an election for a specific
elector
Store: Don't need this since it's already implemented by
CandidateRankController@store
Show: Show the rank for a specific candidate of an election for a specific
elector
Put: Update the rank for a specific candidate of an election for a specific
elector

I think Tyler and Nathan were working on some of this functionality at the
last work session. I think they wrote it in an existing api controller
rather than creating a new one. There should already be functionality
equivalent to the index endpoint that you mentioned. Store is indeed
already implemented. Put should already be supported, but in a bulk fashion
(many ranks in one request). The show endpoint sounds like the endpoint you
described in question 2. Do we need it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pivot-libre/pivot/issues/44>, or mute the thread

**Comment by carlschroedl** [comment]
@aditya-cherukuri Do you feel this has been addressed in #47?

**Comment by carlschroedl** [comment]
This has been resolved. Thanks for opening!
