### ISSUE TITLE
Users' emails are confirmed on registration

### ISSUE THREAD

**Issue by carlschroedl** [pivot-libre/pivot#61]
As any user I want emails to be confirmed on account creation so that no one impersonates me.

**Comment by tylerharter** [comment]
@neckberg: I implemented the backend for this, as well as a hacky frontend.  Passing this off to you so you can make a decent frontend.  Right now, the flow is this:

1. user goes to https://homestead.test/verify_email
2. types an email and clicks verify; this generates a token that is stored and our db and emailed to the user
3. user gets email that encodes email and verification token in url, something like this: "Continue your registration here: http://homestead.test/register?token=4c6839ba8283c85ef9ef85d9fdbbfb6ec399258831e3e864dfaf4705795d6771&email=pivotlibre@gmail.com"
4. user follows that link, which populates the email and a new verification field here: https://homestead.test/register
5. if the verification code is valid, good; if not, it fails in an ugly way (I'll work on that)

For testing purposes, I currently don't check the verification code if it's empty.  That's for our own convenience, and it will be easy to change later when real users use the app.

Maybe you can modify the front end so users trying to register are taken directly to https://homestead.test/verify_email.  That page currently is based on alert popups because I didn't know how to make something slicker.

**Comment by tylerharter** [comment]
Btw, remember to run "php artisan migrate" since I added a new table.

**Comment by tylerharter** [comment]
We added this as an option, so closing (we should eventually enable it).
