### ISSUE TITLE
EAs can see who has voted in an election

### ISSUE THREAD

**Issue by carlschroedl** [pivot-libre/pivot#63]
EAs can see who has voted in an election so that they can decide whether to get the result of the election.

**Comment by carlschroedl** [comment]
We aspire to ... 
 * add a boolean `approved` flag to the Ballot model
 * Enable a user to mark their ballot as approved in the web ui
 * Enable a user to mark their approved ballot as unapproved in the web ui
 * Show EA's who among their election's electorate has marked their ballot as approved. (updating the existing API for returning the viewed/accepted info per voter per election)

**Comment by tylerharter** [comment]
@neckberg I added an API for it:

GET election/<ID>/voter_details

It's a lot like the "GET election/<ID>/voter_status" API you've been using, but for each category, it returns a list of voters instead of a count of voters in that category.  For example, you might get something like this:

{u'approved_none': [{u'name': u'User 2', u'email': u'user2-967798@pivot.vote'}], u'outstanding_invites': [], u'approved_previous': [], u'approved_current': []}

There's one caveat: when the voters are in the "outstanding_invites" category, the "name" field will be null.  That's because the invitee might not have created an account yet, so we only know their email (not their name).  So you need to make sure your code using the API handles that.

**Comment by neckberg** [comment]
Electorate page now shows ballot statuses for electors. Need to make it look prettier, but the basic functionality is there, so I'm closing.
